#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]

use libc::c_char;

mod raw {
    include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
}

pub use raw::*;

// Validation layers
const ENABLE_VALIDATION_LAYERS: bool = cfg!(debug_assertions);

unsafe extern "system" fn debug_callback(
    message_severity: crate::VkDebugUtilsMessageSeverityFlagBitsEXT,
    message_type: crate::VkDebugUtilsMessageTypeFlagsEXT,
    p_callback_data: *const crate::VkDebugUtilsMessengerCallbackDataEXT,
    _p_user_data: *mut std::ffi::c_void,
) -> crate::VkBool32 {
    use crate::VkDebugUtilsMessageSeverityFlagBitsEXT as Severity;
    use crate::VkDebugUtilsMessageTypeFlagBitsEXT as Type;
    let severity = match message_severity {
        Severity::VK_DEBUG_UTILS_MESSAGE_SEVERITY_VERBOSE_BIT_EXT => "VERBOSE",
        Severity::VK_DEBUG_UTILS_MESSAGE_SEVERITY_INFO_BIT_EXT => "INFO",
        Severity::VK_DEBUG_UTILS_MESSAGE_SEVERITY_WARNING_BIT_EXT => "WARNING",
        Severity::VK_DEBUG_UTILS_MESSAGE_SEVERITY_ERROR_BIT_EXT => "ERROR",
        _ => "UNKNOWN",
    };
    let type_str = match message_type {
        Type::VK_DEBUG_UTILS_MESSAGE_TYPE_GENERAL_BIT_EXT => "GENERAL",
        Type::VK_DEBUG_UTILS_MESSAGE_TYPE_VALIDATION_BIT_EXT => "VALIDATION",
        Type::VK_DEBUG_UTILS_MESSAGE_TYPE_PERFORMANCE_BIT_EXT => "PERFORMANCE",
        _ => "UNKNOWN",
    };
    let callback_data = &*p_callback_data;
    let message = std::ffi::CStr::from_ptr(callback_data.pMessage);
    eprintln!("[{} {}] {}", severity, type_str, message.to_string_lossy());
    crate::VK_FALSE
}

// SDL window flags (not generated by bindgen)
pub const SDL_WINDOW_VULKAN: u64 = 0x0000000010000000;

// Vulkan version helper
pub fn VK_MAKE_VERSION(major: u32, minor: u32, patch: u32) -> u32 {
    (major << 22) | (minor << 12) | patch
}

// Simple API module
pub mod simple;

pub struct SdlContext {
    _private: (),
}

impl SdlContext {
    pub fn init() -> Result<Self, String> {
        unsafe {
            if !SDL_Init(SDL_INIT_VIDEO) {
                return Err(format!("SDL_Init failed: {}", get_sdl_error()));
            }
        }
    }
}

impl Drop for SdlContext {
    fn drop(&mut self) {
        unsafe {
            SDL_Quit();
        }
    }
}

pub struct VulkanInstance {
    pub instance: crate::VkInstance,
    debug_messenger: Option<crate::VkDebugUtilsMessengerEXT>,
}

impl VulkanInstance {
    pub fn create(_sdl: &SdlContext, _window: &SdlWindow) -> Result<Self, String> {
        unsafe {
            let mut count = 0;
            let extensions_ptr = SDL_Vulkan_GetInstanceExtensions(&mut count);
            if extensions_ptr.is_null() || count == 0 {
                return Err(format!(
                    "SDL_Vulkan_GetInstanceExtensions failed: {}",
                    get_sdl_error()
                ));
            }
            let sdl_extensions = std::slice::from_raw_parts(extensions_ptr, count as usize);
            let mut enabled_extensions: Vec<*const i8> = sdl_extensions.to_vec();
            eprintln!("ENABLE_VALIDATION_LAYERS = {}", ENABLE_VALIDATION_LAYERS);
            eprintln!("debug_assertions = {}", cfg!(debug_assertions));

            // Add debug utils extension if validation layers enabled
            if ENABLE_VALIDATION_LAYERS {
                eprintln!("Adding VK_EXT_debug_utils extension");
                enabled_extensions.push(b"VK_EXT_debug_utils\0".as_ptr() as *const i8);
                eprintln!("Debug utils extension added");
            }

            // Validation layers
            let enabled_layers = if ENABLE_VALIDATION_LAYERS {
                eprintln!("Enabling Vulkan validation layers");
                vec![b"VK_LAYER_KHRONOS_validation\0".as_ptr() as *const i8]
            } else {
                vec![]
            };

            let app_info = VkApplicationInfo {
                sType: VkStructureType::VK_STRUCTURE_TYPE_APPLICATION_INFO,
                pNext: std::ptr::null(),
                pApplicationName: b"Rust Vulkan App\0".as_ptr() as *const c_char,
                applicationVersion: VK_MAKE_VERSION(1, 0, 0),
                pEngineName: b"No Engine\0".as_ptr() as *const c_char,
                engineVersion: VK_MAKE_VERSION(1, 0, 0),
                apiVersion: VK_MAKE_VERSION(1, 2, 0),
            };

            let create_info = VkInstanceCreateInfo {
                sType: VkStructureType::VK_STRUCTURE_TYPE_INSTANCE_CREATE_INFO,
                pNext: std::ptr::null(),
                flags: 0,
                pApplicationInfo: &app_info,
                enabledLayerCount: enabled_layers.len() as u32,
                ppEnabledLayerNames: if enabled_layers.is_empty() {
                    std::ptr::null()
                } else {
                    enabled_layers.as_ptr()
                },
                enabledExtensionCount: enabled_extensions.len() as u32,
                ppEnabledExtensionNames: if enabled_extensions.is_empty() {
                    std::ptr::null()
                } else {
                    enabled_extensions.as_ptr()
                },
            };

            let mut instance = std::ptr::null_mut();
            let result = vkCreateInstance(&create_info, std::ptr::null(), &mut instance);
            if result != VkResult::VK_SUCCESS {
                return Err(format!("vkCreateInstance failed: {:?}", result));
            }
            let debug_messenger = if ENABLE_VALIDATION_LAYERS {
                Self::setup_debug_messenger(instance)
            } else {
                None
            };
            Ok(VulkanInstance {
                instance,
                debug_messenger,
            })
        }
    }
}

impl Drop for VulkanInstance {
    fn drop(&mut self) {
        unsafe {
            if let Some(messenger) = self.debug_messenger {
                crate::vkDestroyDebugUtilsMessengerEXT(self.instance, messenger, std::ptr::null());
            }
            vkDestroyInstance(self.instance, std::ptr::null());
        }
    }
}

pub struct VulkanSurface {
    pub surface: crate::VkSurfaceKHR,
    pub instance: crate::VkInstance,
}

impl VulkanSurface {
    pub fn create(window: &SdlWindow, instance: &VulkanInstance) -> Result<Self, String> {
        unsafe {
            let mut surface = std::ptr::null_mut();
            let success = crate::SDL_Vulkan_CreateSurface(
                window.window,
                instance.instance,
                std::ptr::null(),
                &mut surface,
            );
            if !success {
                return Err(format!(
                    "SDL_Vulkan_CreateSurface failed: {}",
                    get_sdl_error()
                ));
            }
            Ok(VulkanSurface {
                surface,
                instance: instance.instance,
            })
        }
    }
}

impl Drop for VulkanSurface {
    fn drop(&mut self) {
        unsafe {
            crate::SDL_Vulkan_DestroySurface(self.instance, self.surface, std::ptr::null());
        }
    }
}

pub struct VulkanDevice {
    pub surface: Option<VulkanSurface>,
    pub physical_device: crate::VkPhysicalDevice,
    pub device: crate::VkDevice,
    pub graphics_queue: crate::VkQueue,
    pub present_queue: crate::VkQueue,
    pub command_pool: crate::VkCommandPool,
    pub instance: VulkanInstance,
}

impl VulkanDevice {
    pub fn create(
        instance: VulkanInstance,
        surface: Option<VulkanSurface>,
    ) -> Result<Self, String> {
        eprintln!("VulkanDevice::create enter");
        unsafe {
            // Enumerate physical devices
            let mut device_count = 0;
            let result = crate::vkEnumeratePhysicalDevices(
                instance.instance,
                &mut device_count,
                std::ptr::null_mut(),
            );
            if result != crate::VkResult::VK_SUCCESS || device_count == 0 {
                return Err(format!(
                    "Failed to enumerate physical devices: {:?}",
                    result
                ));
            }
            eprintln!("Found {} physical devices", device_count);

            let mut physical_devices = Vec::with_capacity(device_count as usize);
            let result = crate::vkEnumeratePhysicalDevices(
                instance.instance,
                &mut device_count,
                physical_devices.as_mut_ptr(),
            );
            if result != crate::VkResult::VK_SUCCESS {
                return Err(format!("Failed to get physical devices: {:?}", result));
            }
            physical_devices.set_len(device_count as usize);

            // Select a suitable physical device
            let physical_device = physical_devices
                .into_iter()
                .next()
                .ok_or("No Vulkan physical devices found".to_string())?;
            eprintln!("Selected physical device");

            // Get queue family properties
            let mut queue_family_count = 0;
            crate::vkGetPhysicalDeviceQueueFamilyProperties(
                physical_device,
                &mut queue_family_count,
                std::ptr::null_mut(),
            );
            let mut queue_families = Vec::with_capacity(queue_family_count as usize);
            crate::vkGetPhysicalDeviceQueueFamilyProperties(
                physical_device,
                &mut queue_family_count,
                queue_families.as_mut_ptr(),
            );
            queue_families.set_len(queue_family_count as usize);

            // Find graphics queue family index
            let graphics_queue_family_index = queue_families
                .iter()
                .position(|props| {
                    props.queueFlags & (crate::VkQueueFlagBits::VK_QUEUE_GRAPHICS_BIT as u32) != 0
                })
                .ok_or("No graphics queue family found".to_string())?
                as u32;
            eprintln!(
                "Graphics queue family index: {}",
                graphics_queue_family_index
            );

            // Find present queue family index (if surface exists)
            let present_queue_family_index = if let Some(ref surf) = surface {
                let mut present_support = 0u32;
                let mut index = 0;
                for (i, _) in queue_families.iter().enumerate() {
                    let result = crate::vkGetPhysicalDeviceSurfaceSupportKHR(
                        physical_device,
                        i as u32,
                        surf.surface,
                        &mut present_support,
                    );
                    if result == crate::VkResult::VK_SUCCESS && present_support != 0 {
                        index = i as u32;
                        break;
                    }
                }
                if present_support == 0 {
                    return Err("No present queue family found".to_string());
                }
                index
            } else {
                graphics_queue_family_index // same as graphics if no surface
            };
            eprintln!("Present queue family index: {}", present_queue_family_index);

            // Create logical device
            eprintln!("Creating logical device...");
            let queue_priorities = [1.0f32];
            let mut queue_create_infos = Vec::new();

            let graphics_queue_info = crate::VkDeviceQueueCreateInfo {
                sType: crate::VkStructureType::VK_STRUCTURE_TYPE_DEVICE_QUEUE_CREATE_INFO,
                pNext: std::ptr::null(),
                flags: 0,
                queueFamilyIndex: graphics_queue_family_index,
                queueCount: 1,
                pQueuePriorities: queue_priorities.as_ptr(),
            };
            queue_create_infos.push(graphics_queue_info);

            if graphics_queue_family_index != present_queue_family_index {
                let present_queue_info = crate::VkDeviceQueueCreateInfo {
                    sType: crate::VkStructureType::VK_STRUCTURE_TYPE_DEVICE_QUEUE_CREATE_INFO,
                    pNext: std::ptr::null_mut(),
                    flags: 0,
                    queueFamilyIndex: present_queue_family_index,
                    queueCount: 1,
                    pQueuePriorities: queue_priorities.as_ptr(),
                };
                queue_create_infos.push(present_queue_info);
            }

            // Required device extensions
            let mut enabled_extensions = Vec::new();
            if surface.is_some() {
                enabled_extensions.push(b"VK_KHR_swapchain\0".as_ptr() as *const i8);
            }
            // Enable buffer device address extension for GPU pointers
            enabled_extensions.push(b"VK_KHR_buffer_device_address\0".as_ptr() as *const i8);
            // Enable descriptor buffer extension for bindless textures
            enabled_extensions.push(b"VK_EXT_descriptor_buffer\0".as_ptr() as *const i8);
            // Enable scalar block layout for GLSL scalar layout
            enabled_extensions.push(b"VK_EXT_scalar_block_layout\0".as_ptr() as *const i8);
            // Enable buffer reference for GLSL buffer_reference extension (optional)
            // enabled_extensions.push(b"VK_EXT_buffer_reference\0".as_ptr() as *const i8);
            eprintln!("Enabled device extensions:");
            for ext in &enabled_extensions {
                eprintln!("  {:?}", std::ffi::CStr::from_ptr(*ext)); // unsafe but we know they are zero-terminated
            }

            // Scalar block layout feature
            let mut scalar_block_layout_features = crate::VkPhysicalDeviceScalarBlockLayoutFeatures {
                sType: crate::VkStructureType::VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SCALAR_BLOCK_LAYOUT_FEATURES_EXT,
                pNext: std::ptr::null_mut(),
                scalarBlockLayout: 1,
            };

            // Descriptor buffer feature (must be before buffer device address in chain)
            let mut descriptor_buffer_features = crate::VkPhysicalDeviceDescriptorBufferFeaturesEXT {
                sType: crate::VkStructureType::VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_DESCRIPTOR_BUFFER_FEATURES_EXT,
                pNext: std::ptr::null_mut(),
                descriptorBuffer: 1,
                descriptorBufferCaptureReplay: 0,
                descriptorBufferImageLayoutIgnored: 0,
                descriptorBufferPushDescriptors: 0,
            };

            // Buffer device address feature
            let mut buffer_device_address_features = crate::VkPhysicalDeviceBufferDeviceAddressFeatures {
                sType: crate::VkStructureType::VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_BUFFER_DEVICE_ADDRESS_FEATURES,
                pNext: &mut descriptor_buffer_features as *mut _ as *mut libc::c_void,
                bufferDeviceAddress: 1,
                bufferDeviceAddressCaptureReplay: 0,
                bufferDeviceAddressMultiDevice: 0,
            };

            // Chain scalar -> buffer device address -> descriptor buffer
            scalar_block_layout_features.pNext =
                &mut buffer_device_address_features as *mut _ as *mut libc::c_void;

            let device_create_info = crate::VkDeviceCreateInfo {
                sType: crate::VkStructureType::VK_STRUCTURE_TYPE_DEVICE_CREATE_INFO,
                pNext: &mut scalar_block_layout_features as *mut _ as *mut libc::c_void,
                flags: 0,
                queueCreateInfoCount: queue_create_infos.len() as u32,
                pQueueCreateInfos: queue_create_infos.as_ptr(),
                enabledLayerCount: 0,
                ppEnabledLayerNames: std::ptr::null(),
                enabledExtensionCount: enabled_extensions.len() as u32,
                ppEnabledExtensionNames: if enabled_extensions.is_empty() {
                    std::ptr::null()
                } else {
                    enabled_extensions.as_ptr()
                },
                pEnabledFeatures: std::ptr::null(),
            };

            eprintln!("Calling vkCreateDevice...");
            let mut device = std::ptr::null_mut();
            let result = crate::vkCreateDevice(
                physical_device,
                &device_create_info,
                std::ptr::null(),
                &mut device,
            );
            if result != crate::VkResult::VK_SUCCESS {
                eprintln!("vkCreateDevice failed: {:?}", result);
                return Err(format!("Failed to create logical device: {:?}", result));
            }
            eprintln!("Logical device created successfully");

            // Get queues
            let mut graphics_queue = std::ptr::null_mut();
            crate::vkGetDeviceQueue(device, graphics_queue_family_index, 0, &mut graphics_queue);
            let mut present_queue = std::ptr::null_mut();
            crate::vkGetDeviceQueue(device, present_queue_family_index, 0, &mut present_queue);

            // Create command pool
            let command_pool_info = crate::VkCommandPoolCreateInfo {
                sType: crate::VkStructureType::VK_STRUCTURE_TYPE_COMMAND_POOL_CREATE_INFO,
                pNext: std::ptr::null(),
                flags: crate::VkCommandPoolCreateFlagBits::VK_COMMAND_POOL_CREATE_RESET_COMMAND_BUFFER_BIT as u32,
                queueFamilyIndex: graphics_queue_family_index,
            };

            let mut command_pool = std::ptr::null_mut();
            let result = crate::vkCreateCommandPool(
                device,
                &command_pool_info,
                std::ptr::null(),
                &mut command_pool,
            );
            if result != crate::VkResult::VK_SUCCESS {
                crate::vkDestroyDevice(device, std::ptr::null());
                return Err(format!("Failed to create command pool: {:?}", result));
            }

            Ok(VulkanDevice {
                surface,
                physical_device,
                device,
                graphics_queue,
                present_queue,
                command_pool,
                instance,
            })
        }
    }

    pub fn graphics_context(&self) -> simple::Result<simple::GraphicsContext> {
        simple::GraphicsContext::new(
            self.instance.instance,
            self.physical_device,
            self.device,
            self.graphics_queue,
            self.present_queue,
            self.command_pool,
        )
    }
}

impl Drop for VulkanDevice {
    fn drop(&mut self) {
        unsafe {
            crate::vkDestroyCommandPool(self.device, self.command_pool, std::ptr::null());
            crate::vkDestroyDevice(self.device, std::ptr::null());
        }
    }
}

pub struct SdlWindow {
    window: *mut SDL_Window,
}

impl SdlWindow {
    pub fn new(title: &str, width: i32, height: i32) -> Result<Self, String> {
        unsafe {
            let window = SDL_CreateWindow(
                title.as_ptr() as *const c_char,
                width,
                height,
                SDL_WINDOW_VULKAN,
            );
            if window.is_null() {
                return Err(format!("SDL_CreateWindow failed: {}", get_sdl_error()));
            }
            Ok(SdlWindow { window })
        }
    }
}

impl Drop for SdlWindow {
    fn drop(&mut self) {
        unsafe {
            SDL_DestroyWindow(self.window);
        }
    }
}

fn get_sdl_error() -> String {
    unsafe {
        let error = SDL_GetError();
        std::ffi::CStr::from_ptr(error)
            .to_string_lossy()
            .into_owned()
    }
}
